#!/usr/bin/env bash
#A bash script that transfers a file from our client toa server.
#Accepts 4Parameters- Path to the file to be transfered - the ip of the server to transfer the file to -the username scp connects with -the path to the ssh private key that scp uses
#Display Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY if less than 3 parameters passed

if [ "$4" ];
then
	scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3@$2:~"
elif [ "$3" ]; then 
	scp -o StrictHostKeyChecking=no "$1" "$3@$2~"
else
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY";
fi
