#!/usr/bin/env bash
#install a webserver nginx on web-01
#requirements
#+	should listen to port 80
#+	When querying Nginx at its root / with a GET request (requesting a page) using curl, it must return a page that contains the string Hello World!
#+	write a Bash script that configures a new Ubuntu machine to respect above requirements (this script will be run on the server itself)

sudo apt-get update
sudo apt-get install -y nginx

sudo mkdir /etc/nginx/html
sudo touch /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/html/index.html
sed -i "/listen \[::]:80 default_server;/a\;" > /etc/nginx/sites-available/default

sudo service nginx restart
