#!/usr/bin/env bash
#Configure your Nginx server so that /redirect_me is redirecting to another page.
#The redirection must be a “301 Moved Permanently”
#You answer file should be a Bash script containing commands to automatically
#configure a Ubuntu machine to respect above requirements
#Using what you did with 1-install_nginx_web_server,
#write 3-redirection so that it configures a brand new Ubuntu machine to the requirements.

sudo apt-get update -y
sudo apt-get install -y nginx

sudo mkdir /etc/nginx/html
sudo touch /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/html/index.html

sed -i "/listen\[::]:80 default_server;/a\  rewrite ^/redirect_me/?.*$ https://www.youtube.com/watch?v=QH2-TGUlwu4;" /etc/nginx/sites-available/default

sudo service nginx restart
