#!/usr/bin/env bash
#Configure your Nginx server to have a custom 404 page that contains
#the string Ceci n'est pas une page.
#The page must return an HTTP 404 error code
#The page must contain the string Ceci n'est pas une page
#Using what you did with 3-redirection,
#write 4-not_found_page_404 so that it configures a brand new Ubuntu
#machine to the requirements asked in this task

sudo apt-get update -y
sudo apt-get install -y nginx

sudo mkdir /etc/nginx/html
sudo touch /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/html/index.html
sudo touch /etc/nginx/html/404.html
echo "Ceci n'est pas une page" > /etc/nginx/html/404.html

sed -i "/listen \[::]:80 default_server;/a\	rewrite ^/redirect_me/?.*$ https://www.youtube.com/watch?v=QH2-TGUlwu4;" /etc/nginx/sites-available/defaut
sed -i "/listen \[::]:80 default_server;/a\	error_page 404 /404.html;" /etc/nginx/sites-available/defaul
