#!/usr/bin/env bash
#Configure web-02 to be identical to web-01.
#Add a custom Nginx response header to be able to rack which webswerver is answering the HTTPs requests.shouldd containd a custom header(on web-01 and web-02)
#the name of the custom HTTP header must be X-Served-By
#the value of the custom HTTP header must be a host name of the server Nginx is running on
#setup nginx web server, including 301 redirect, 404, and HTTP response header
#ignore SC2154

sudo apt-get -y update
sudo apt-get -y install nginx

sudo mkdir /etc/nginx/html
sudo touch /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/html/index.html

sudo touch /etc/nginx/html/404.html
echo "Ceci n'est pas une page" > /etc/nginx/html/404.html

printf %s "server {
	listen 80;
	listen [::]:80 default_server;
	add_header X-Served-By $HOSTNAME;
	root	/etc/nginx/html;
	index	index.html index.htm;
	location /redirect_me {
		return https://www.youtube.com/watch?v=mTEros927Ow permanent;;
	}
	error_page 404 /404.html;
	location /404 {
		root /etc/nginx/html;
		internal;
	}
}" > /etc/nginx/sites-avalable/default

sudo services nginx restart
