#!/usr/bin/env bash
#install and configure HAproxy on the lb-01 server
#Requirements
#+	Configure HAproxy so that it send traffic to web-01 and web-02
#+	Distribute requests using a roundrobin algorithm
#+	Make sure that HAproxy can be managed via an init script
#+	Make sure that your servers are configured with the right hostnames: [STUDENT_ID]-web-01 and [STUDENT_ID]-web-02

sodu apt-get -y update
sodu apt-get -y install haproxy

echo "Enabled=1" >> /etc/default/haproxy
sudo mv /etc/haproxy/haproxy.cfg{,.original}
sudo touch /etc/haproxy/haproxy.cfg

printf %s "global
	log 127.0.0.1 local0 notice
	maxconn 2000
	user haproxy
	group haproxy

defaults
	log     global
	mode    http
	option  httplog
	option  dontlognull
	retries 3
	option redispatch

listen hbnb
	bind	0.0.0.0.80
	mode	http
	stats	enable
	stats url /haproxy?stats
	balance	roundrobin
	option	httpclose
	option	forwardfor
	server	web-01 34.75.35.59 check
	server	web-02 3.238.29.119 check
	" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
