#!/usr/bin/env bash
#Displays "Best School" 10 times using the while loop
#On the 9th, diplay "Hi" and continue

num=0

while [ $num -lt 10 ]
do
  if [ $num -eq 9 ]
  then
    echo "Hi"
  fi
  echo "Best School"
  (( num++ ))
done
