#!/usr/bin/env bash
#Displays The content of the current directory
#In a list format
#Where only the part of the name after the first dash is displayed

list=$(ls)
for c in $list; do
	echo "$c" | cut -d '-' -f2
done
